# Generated by Django 2.2.19 on 2021-08-18 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('date_pz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mfc',
            name='publicId',
        ),
    ]
